package Trie;

public class LocomotiveTrieTest {

	public static void main(String[] args) 
	{
		// TODO Auto-generated method stub
		LocomotiveTrie test = new LocomotiveTrie(); //create new 'LocomotiveTrie' object
		
		Locomotive loco1, loco2, loco3, loco4, loco5, loco6, loco7, loco8, loco9, loco10, loco11, loco12, loco13, loco14, loco15, loco16;
		Locomotive loco17, loco18, loco19, loco20, loco21, loco22, loco23, loco24, loco25, loco26, loco27, loco28, loco29, loco30, loco31;
		Locomotive loco32, loco33, loco34, loco35, loco36, loco37, loco38, loco39, loco40;
		Locomotive loco41, loco42, loco43, loco44, loco45, loco46, loco47, loco48, loco49, loco50, loco51, loco52, loco53, loco54, loco55, loco56, loco57, loco58, loco59, loco60;
		Locomotive loco61, loco62, loco63, loco64, loco65, loco66, loco67, loco68, loco69, loco70;
		Locomotive loco71, loco72, loco73;

		loco1 = new Locomotive("Percy", 6, true, "Avonside Saddle Tank", "green");
		loco2 = new Locomotive("Billy", null, false, "Manning Wardle L", "orange");
		loco3 = new Locomotive("Fergus", null, false, "Blue Circle", "royal blue");
		loco4 = new Locomotive("Smudger", null, false, "Dolgoch", "green");
		loco5 = new Locomotive("Luke", 22, true, "Kerr Stuart Wren", "green");
		loco6 = new Locomotive("Henry", 3, true, "LMS Black 5", "green");
		loco7 = new Locomotive("Derek", null, false, "BR Class 17", "dark green");
		loco8 = new Locomotive("Arthur", 41241, true, "LMS Ivatt 2MT", "red");
		loco9 = new Locomotive("'Arry", null, false, "BR Class 08", "dark green and yellow");
		loco10 = new Locomotive("Rebecca", 22, true, "SR West Country Class", "yellow");
		loco11 = new Locomotive("Murdoch", null, false, "BR Standard 9F", "orange");
		loco12 = new Locomotive("Sidney", null, false, "BR Class 08", "dark blue");
		loco13 = new Locomotive("Norman", null, false, "BR Class 11001", "red");
		loco14 = new Locomotive("Dennis", 11001, true, "BR Class 11001", "grey");
		loco15 = new Locomotive("Hank", null, false, "PRR K4 Pacific", "royal blue");
		loco16 = new Locomotive("Belle", 6120, true, "LMS Ivatt 4MT", "prussian blue");
		loco17 = new Locomotive("Bill", 1, true, "Alfredy and Judy", "golden yellow");
		loco18 = new Locomotive("Bertram", null, false, "Small England", "dark brown");
		loco19 = new Locomotive("Bash", null, false, "Bear Harbor Lumber Company 1", "blue and orange");
		loco20 = new Locomotive("Neville", 30010, true, "SR Bulleid Q1", "black");
		loco21 = new Locomotive("Donald", 9, true, "CR 812", "black");
		loco22 = new Locomotive("Daisy", null, false, "BR Class 101", "green");
		loco23 = new Locomotive("Ryan", 1014, true, "GNR N2", "purple");
		loco24 = new Locomotive("Hugo", null, false, "Schienenzeppelin", "silver");
		loco25 = new Locomotive("James", 5, true, "L&YR Class 28", "red");
		loco26 = new Locomotive("Douglas", 10, true, "CR 812", "black");
		loco27 = new Locomotive("Rheneas", 2, true, "\"Dolgoch\"", "crimson");
		loco28 = new Locomotive("Ferdinand", null, false, "Climax Class C", "teal");
		loco29 = new Locomotive("Emily", 12, true, "GNR Stirling Single", "emerald");
		loco30 = new Locomotive("Victor", 1173, true, "\"Minaz\" No. 1173", "yellow and green");
		loco31 = new Locomotive("James", 5, true, "L&YR Class 28", "black");
		loco32 = new Locomotive("Gordon", 4, true, "LNER A3 Pacific", "blue");
		loco33 = new Locomotive("Den", null, false, "Rolls Royce Sentinel Hydraulic", "blue and orange");
		loco34 = new Locomotive("Dart", null, false, "Bagnall Diesel Shunter", "crimson and yellow");
		loco35 = new Locomotive("Duke", null, false, "Small England", "brown");
		loco36 = new Locomotive("Thomas", 70, true, "LBSCR E2", "green");
		loco37 = new Locomotive("Harvey", 27, true, "Dubs Crane Tank", "maroon");
		loco38 = new Locomotive("Salty", 2991, true, "BR Class 07", "green");
		loco39 = new Locomotive("Spencer", null, false, "LNER A4 Pacific", "silver");
		loco40 = new Locomotive("BoCo", null, false, "BR Class 28", "green");
		loco41 = new Locomotive("Glynn", 1, true, "Head and Wrightson 0-4-0VBT", "red");
		loco42 = new Locomotive("Stepney", 55, true, "LBSCR A1x Terrier \"Stepney\"", "goldenrod");
		loco43 = new Locomotive("Paxton", null, false, "BR Class 08", "dark green");
		loco44 = new Locomotive("Hiro", 51, true, "JNR D51", "black");
		loco45 = new Locomotive("Splatter", null, false, "BR Class 08", "purple");
		loco46 = new Locomotive("Yong Bao", null, false, "China Railways RM Pacific", "red");
		loco47 = new Locomotive("Samson", null, false, "High Harrington Ironworks Saddletank", "viridian");
		loco48 = new Locomotive("Thomas", 1, true, "LBSCR E2", "blue");
		loco49 = new Locomotive("Diesel", null, false, "BR Class 08", "black");
		loco50 = new Locomotive("Mavis", null, false, "BR Class 04", "black");
		loco51 = new Locomotive("Molly", null, false, "\"Claud Hamilton\"", "yellow");
		loco52 = new Locomotive("Toby", 7, true, "LNER J70", "brown");
		loco53 = new Locomotive("Frankie", 4002, true, "MSC 4002", "blue-green and black");
		loco54 = new Locomotive("Hurricane", 20, true, "GER A55 \"Decapod\"", "red");
		loco55 = new Locomotive("Skiff", null, false, "Eastport Pram", "white");
		loco56 = new Locomotive("Edward", 2, true, "FR K2 \"Larger Seagulls\"", "blue");
		loco57 = new Locomotive("Salty", 2991, true, "BR Class 07", "red");
		loco58 = new Locomotive("Mighty Mac", null, false, "Double Fairlie", "royal blue");
		loco59 = new Locomotive("Skarloey", 1, true, "\"Tallylyn\"", "red");
		loco60 = new Locomotive("Flying Scotsman", 4472, true, "LNER A3 \"Flying Scotsman\"", "dark green");
		loco61 = new Locomotive("Whiff", null, false, "NER 66 \'Aerolite\"", "dark green");
		loco62 = new Locomotive("Hercules", 6, true, "\"Hercules\"", "black hull, yellow superstructure, red stack, white and blue funnel, white and blue cap");
		loco63 = new Locomotive("Stafford", 1917, true, "North Staffordshire Railway Battery-Electric No 1", "brown");
		loco64 = new Locomotive("Richard", 778, true, "SR N15", "dark green");
		loco65 = new Locomotive("Duck", 8, true, "GWR 57XX Pannier", "green");
		loco66 = new Locomotive("Terence", null, false, "Caterpillar Model 70", "orange");
		loco67 = new Locomotive("Merlin", 783, true, "SR N15", "silver");
		loco68 = new Locomotive("Trevor", null, false, "Aveling and Porter Foster Traction Engine", "dark green");
		loco69 = new Locomotive("Porter", null, false, "H.K. Porter 0-6-0ST", "viridian");
		loco70 = new Locomotive("Bear", null, false, "BR Class 35 \"Hymek\"", "green");
		loco71 = new Locomotive("Hector", null, false, "ICB Coal Hopper", "black");
		loco72 = new Locomotive("Top Hat", 4, true, "New York Central Tugboat 13", "black hull, yellow superstructure, red stack, white and blue funnel, brown wheelhouse");
		loco73 = new Locomotive("Bradford", null, false, "LMS 20 Ton Brakevan", "green");
		
		// test.addOccurrence(loco33);
		// test.addOccurrence(loco14);
		// test.removeOccurrence(loco33);
		// test.removeOccurrence(loco33);

		// test.addOccurrence(loco21);
		// test.addOccurrence(loco26);
		// test.removeOccurrence(loco21);
		// test.removeOccurrence(loco21);

		test.addOccurrence(loco56); //add 'name' field of 'loco56' to 'test'
		test.addOccurrence(loco62);
		test.addOccurrence(loco17);
		test.addOccurrence(loco56);
		test.addOccurrence(loco56);
		test.addOccurrence(loco34);
		test.addOccurrence(loco56);
		test.addOccurrence(loco38);
		test.addOccurrence(loco22);
		test.addOccurrence(loco5);
		test.addOccurrence(loco62);
		test.addOccurrence(loco62);
		test.addOccurrence(new Locomotive("Bowler", 261, true, "BR Class 40", "dark green"));
		test.addOccurrence(loco31);
		test.addOccurrence(loco70);
		test.addOccurrence(loco44);
		test.addOccurrence(loco12);
		test.addOccurrence(loco31);
		test.addOccurrence(loco22);
		test.addOccurrence(loco44);
		test.addOccurrence(loco64);
		test.addOccurrence(loco6);
		test.addOccurrence(loco62);
		test.addOccurrence(loco21);
		test.addOccurrence(loco52);
		test.addOccurrence(loco14);
		test.addOccurrence(loco57);
		test.addOccurrence(loco32);
		test.addOccurrence(loco52);
		test.addOccurrence(loco49);
		test.addOccurrence(loco2);
		test.addOccurrence(loco68);
		test.addOccurrence(loco17);
		test.addOccurrence(loco44);
		test.addOccurrence(loco31);
		test.addOccurrence(loco33);
		test.addOccurrence(loco62);
		test.addOccurrence(loco1);
		test.addOccurrence(loco25);
		test.addOccurrence(loco1);
		test.removeOccurrence(loco71);
		test.removeOccurrence(loco72);
		test.addOccurrence(loco23);
		test.addOccurrence(loco39);
		test.addOccurrence(loco31);
		test.addOccurrence(new Locomotive("Charlie", 14, true, "Manning Wardle L", "purple"));
		test.addOccurrence(loco12);
		test.addOccurrence(loco39);
		test.addOccurrence(new Locomotive("Dash", null, false, "Bear Harbor Lumber Company 1", "blue and orange"));
		test.addOccurrence(loco13);
		test.addOccurrence(loco51);
		test.addOccurrence(loco68);
		test.addOccurrence(new Locomotive("Spamcan", 199, true, "BR Class 46", "light blue"));
		test.addOccurrence(new Locomotive("O.J.", 3, true, "Eppleton Hall", "yellow superstructure, black hull, red stack, white and blue funnel, white paddlehouses"));
		test.addOccurrence(loco17);
		test.addOccurrence(loco22);
		test.addOccurrence(loco8);
		test.addOccurrence(loco11);
		test.addOccurrence(loco29);
		test.addOccurrence(loco66);
		test.addOccurrence(loco32);
		test.addOccurrence(loco56);
		test.addOccurrence(loco2);
		test.addOccurrence(new Locomotive("Ben ", 2, true, "Alfred and Judy", "dark blue"));
		test.addOccurrence(loco66);
		test.addOccurrence(loco6);
		test.addOccurrence(loco8);
		test.addOccurrence(new Locomotive("Donald  ", 9, true, "CR 812", "blue"));
		test.addOccurrence(new Locomotive("Bert", null, false, "BR Class 08", "dark green and yellow"));
		test.addOccurrence(loco72);
		test.addOccurrence(loco35);
		test.addOccurrence(loco42);
		test.addOccurrence(loco11);
		test.addOccurrence(loco25);
		test.addOccurrence(loco6);
		test.addOccurrence(new Locomotive("Bill", 1, true, "Alfred and Judy", "dark blue"));
		test.addOccurrence(loco6);
		test.addOccurrence(loco48);
		test.addOccurrence(loco35);
		test.addOccurrence(loco1);
		test.addOccurrence(loco29);
		test.addOccurrence(new Locomotive("Grampus", null, false, "U.S.S. Grampus", "grey"));
		test.addOccurrence(loco18);
		test.addOccurrence(loco20);
		test.addOccurrence(loco62);
		test.addOccurrence(loco30);
		test.addOccurrence(new Locomotive("James", 5, true, "L&YR Class 28", "pink"));
		test.addOccurrence(loco6);
		test.addOccurrence(loco9);
		test.addOccurrence(loco42);
		test.addOccurrence(new Locomotive("Oliver", 11, true, "GWR 14XX", "green"));
		test.addOccurrence(new Locomotive("Douglas~~", 10, true, "CR 812", "blue"));
		test.addOccurrence(loco29);
		test.addOccurrence(new Locomotive("Victor", null, false, "\"Minaz\" No. 1173", "red and yellow"));
		test.addOccurrence(loco56);
		test.addOccurrence(loco36);
		test.addOccurrence(loco62);
		test.addOccurrence(loco14);
		test.addOccurrence(loco19);
		test.addOccurrence(loco42);
		test.addOccurrence(loco20);
		test.addOccurrence(loco57);
		test.addOccurrence(loco30);
		test.addOccurrence(loco65);
		test.addOccurrence(loco56);
		test.addOccurrence(loco40);
		test.addOccurrence(loco35);
		test.addOccurrence(new Locomotive("Caroline", null, false, "1926 Morris Oxford Bullnose", "red"));
		test.addOccurrence(loco2);
		test.addOccurrence(new Locomotive("Toad", null, false, "GWR Toad", "grey"));
		test.addOccurrence(loco38);
		test.addOccurrence(loco30);
		test.addOccurrence(new Locomotive("Lady", null, false, "N/A", "purple"));
		test.addOccurrence(loco62);
		test.addOccurrence(loco71);
		test.addOccurrence(loco44);
		test.addOccurrence(loco57);
		test.addOccurrence(loco56);
		test.addOccurrence(loco30);
		test.addOccurrence(loco64);
		test.addOccurrence(loco28);
		test.addOccurrence(new Locomotive("George", null, false, "Aveling & Porter Steam Roller", "green"));
		test.addOccurrence(loco21);
		test.addOccurrence(new Locomotive("Bertie", null, false, "AEC Regal \"T Class\" London Country Area Bus", "red"));
		test.addOccurrence(loco26);
		test.addOccurrence(new Locomotive("Wilbert", null, false, "Hunslet Austerity 0-6-0ST", "blue"));
		test.addOccurrence(new Locomotive("Victor", null, false, "\"Minaz\" No. 1173", "red and yellow"));
		test.addOccurrence(new Locomotive("Bill", 1, true, "Alfred and Judy", "dark blue"));

		test.search(loco8); //searches for # of times 'name' of 'loco8' occurs in trie
		test.search(loco11);
		test.search(loco62);
		test.search(loco2);
		test.search(loco25);
		test.search(loco18);
		test.search(loco3);
		test.search(loco51);
		test.search(loco30);
		test.search(loco44);
		test.search(loco56);
		test.search(loco17);

		System.out.println("Test currently looks like...");
		test.display();

		System.out.println("\n\nGonna remove and add some stuff...");
		test.removeOccurrence(loco17); //removes 1 occurrence of 'loco17' in trie
		test.removeOccurrence(loco32);
		test.removeOccurrence(loco14);
		test.removeOccurrence(loco57);
		test.removeOccurrence(loco2);
		test.removeOccurrence(loco8);
		test.removeOccurrence(loco9);
		test.removeOccurrence(loco12);
		test.removeOccurrence(new Locomotive("O.J.", 3, true, "Eppleton Hall", "yellow superstructure, black hull, red stack, white and blue funnel, white paddlehouses"));
		test.removeOccurrence(loco30);
		test.removeOccurrence(loco2);
		test.removeOccurrence(loco68);
		test.removeOccurrence(loco13);
		test.removeOccurrence(loco18);
		test.addOccurrence(loco7);
		test.removeOccurrence(loco57);
		test.removeOccurrence(new Locomotive("Bowler", 261, true, "BR Class 40", "dark green"));
		test.removeOccurrence(loco51);
		test.removeOccurrence(loco2);
		test.addOccurrence(new Locomotive("Philip", 68, true, "PRR A6 Boxcab", "green and yellow"));
		test.removeOccurrence(new Locomotive("Dash", null, false, "Bear Harbor Lumber Company 1", "blue and orange"));
		test.removeOccurrence(loco66);
		test.removeOccurrence(new Locomotive("Charlie", 14, true, "Manning Wardle L", "purple"));
		test.removeOccurrence(loco2);
		test.addOccurrence(loco3);
		test.addOccurrence(loco4);
		test.removeOccurrence(loco31);
		test.removeOccurrence(loco28);
		test.addOccurrence(loco36);
		test.removeOccurrence(loco44);
		test.removeOccurrence(loco20);
		test.addOccurrence(loco3);
		test.removeOccurrence(loco20);
		test.removeOccurrence(loco11);
		test.removeOccurrence(loco35);
		test.removeOccurrence(loco20);
		test.removeOccurrence(new Locomotive("Spamcan", 199, true, "BR Class 46", "light blue"));
		test.removeOccurrence(loco54);
		test.removeOccurrence(loco19);
		test.removeOccurrence(new Locomotive("Bert ", null, false, "BR Class 08", "yellow and dark green"));
		test.removeOccurrence(loco17);
		test.removeOccurrence(loco25);
		test.removeOccurrence(loco24);
		test.removeOccurrence(loco17);
		test.removeOccurrence(loco23);
		test.removeOccurrence(loco22);
		test.removeOccurrence(loco30);
		test.removeOccurrence(loco42);
		test.removeOccurrence(loco50);
		test.removeOccurrence(loco39);
		test.removeOccurrence(loco29);
		test.removeOccurrence(loco20);
		test.removeOccurrence(loco31);
		test.addOccurrence(new Locomotive("Zorran", 1, true, "1920's Moran Fleet", "brown and blakc"));
		test.removeOccurrence(loco18);

		test.search(loco8); //searches for # of times 'name' of 'loco8' occurs in trie
		test.search(loco11);
		test.search(loco62);
		test.search(loco25);
		test.search(loco18);
		test.search(loco3);
		test.search(loco51);
		test.search(loco30);
		test.search(loco56);
		test.search(loco44);
		test.search(loco17);
		test.search(loco2);

		test.display();
	}

}
